FROM node:alpine

WORKDIR /app

COPY ./package.json ./
RUN npm install

COPY ./nest-cli.json ./
COPY ./tsconfig.build.json ./
COPY ./tsconfig.json ./

COPY ./apps/epts ./apps/epts


CMD ["npm", "run", "start", "--", "epts"]